### PR TITLE
added docs for getting access token

### PR DESCRIPTION
**Pull request by dabit3**
Added documentation for retrieving access token on successful login.

### CODE REVIEW

**Comment by chrisp-fb** [comment]
This looks similar to the existing code snippet in the README. If there's something I misunderstood, let me know.

**Comment by dabit3** [comment]
I did not see any documentation on the AccessToken in the README, maybe I missed it.

**Comment by chrisp-fb** [comment]
How about modifying the snippet above it with usage the AccessToken, rather than duplicating the snippet?

**Comment by dabit3** [comment]
Ah yes, that would work great, I'll go ahead and resubmit.

**Pull request closed without merging**
