### PR TITLE
Move Podspec file to enable react-native link to find it

### PR DESCRIPTION
**Pull request by Titozzz**
Since react-native 0.51, react-native link automatically link this podspec if you have a podfile in your project

### CODE REVIEW

**Comment by thejamespinto** [comment]
@Titozzz can this one be merged?

**Comment by lepouya** [comment]
I looked into this a bit and you're right, it would auto link the podfile
I'm going to keep this open until I'm back in the office so I'd remember to reflect it in the internal codebase as well

**Comment by ifero** [comment]
I am using @Titozzz patch, it works perfectly, please merge it ASAP :)

**Comment by adcuz** [comment]
Please merge, without this the library does not work on the latest RN version.

**Comment by Titozzz** [comment]
@lepouya Are you back ? It's been quite a long time

**Comment by johakr** [comment]
@lepouya any news on this?

**Comment by janicduplessis** [comment]
@Titozzz Thanks for the PR! I can merge this if you fix conflicts.

**Comment by Titozzz** [comment]
on it

**Comment by Titozzz** [comment]
@janicduplessis Done :)

**Pull request merged**
