### PR TITLE
Add Android support for RN 0.48

### PR DESCRIPTION
**Pull request by krystianpach**
In RN 0.48 these lines causes an error.

### CODE REVIEW

**Comment by AndrewJack** [comment]
@krystianpach The code you have removed doesn't cause an error. The `@Override` on the method in v0.6.1 causes the error.

The build error was fixed in #345 & #354, it just hasn't been released yet.

**Comment by philipheinser** [comment]
@AndrewJack Do you know when to expect the release?

**Comment by AndrewJack** [comment]
I don't. Patching or forking is probably your best bet.

https://github.com/facebook/react-native-fbsdk/pull/354#issuecomment-324207945

**Comment by lepouya** [comment]
Yeah The fix from @AndrewJack fixes this problem. I'm going to sync the npm code base with this in a bit

**Comment by jorgedavila25** [comment]
Was this synced up with the npm code base?

**Pull request closed without merging**
