### PR TITLE
Adds LoginManager + GraphRequest example on README

### PR DESCRIPTION
**Pull request by samuelpismel**
An README update, just replace _responseInfoCallback flow args with pure js to improve code coherence.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
@samuelpismel updated the pull request.

**Comment by samuelpismel** [comment]
I've added an working example of LoginManager + GraphRequest with custom permissions and  parameters on the request.

**Comment by facebook-github-bot-6** [comment]
@samuelpismel updated the pull request.

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by dzhuowen** [comment]
Sorry for the late response. Instead of adding this into the huge readme, can you add this example into the HelloFacebook sample app?

**Comment by samuelpismel** [comment]
What is the best way to do this? Create another fork and copy the code to the sample app?

**Comment by jantos** [comment]
@dzhuowen why were @samuelpismel changes to the readme not merged? I understand that you asked him to add it to the sample app, but as long as that is not happening, why not merge his readme changes?

**Comment by abdelhakimkotti** [comment]
No show dialog for permission  ???
Direct connexion no dialog for permission.
Any solution :

_fbAuth() {
 LoginManager.logInWithReadPermissions(['public_profile']).then(
        function(result) {
            if (result.isCancelled) {
                alert('Login cancelled');
            } else {
                alert('Login success with permissions: ' +
                    result.grantedPermissions.toString());
            }
        },
        function(error) {
            alert('Login fail with error: ' + error);
        }
    );
}
bd928362-b21c-4085-ac08-3c478c037c8b

**Pull request closed without merging**
