### PR TITLE
Add setUserID to FBAppEventsLogger

### PR DESCRIPTION
**Pull request by sdduursma**

### CODE REVIEW

**Comment by sdduursma** [comment]
I've now signed the CLA.

**Comment by dzhuowen** [comment]
Can you also add this method for Android? 
https://github.com/facebook/react-native-fbsdk/blob/f27d02831c35a14790b40cc5c1c2381d480b028f/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java

**Comment by sdduursma** [comment]
Hey @dzhuowen, I've added a `setUserID` method for Android as well.

**Comment by bgoyal2222** [comment]
@sdduursma
Hello, I need some help to integrate fb notification as there is no documentation available.. can you tell how to get registrationId from GCM?

**Pull request merged**
