### PR TITLE
add cocoapods install instructions

### PR DESCRIPTION
**Pull request by aghoneim92**
For projects that use cocoapods, rnpm tends to break things. I have tried installing the project using cocoapods by referencing the ios podspec, then following the getting started instructions and it worked.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@aghoneim92 I tried using this and it didn't work for me. Would I still need to include the facebook sdk? Can't you just add:

```
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
```

? Installing fbsdk is a pita. Just adding the pods and the configurations would be much easier.

**Comment by ElvisChiang** [comment]
@RWOverdijk I use this in my own project 

```ruby
pod 'react-native-fbsdk', :subspecs => [
    'Core',
    'Login',
    'Share',
  ], :path => '../node_modules/react-native-fbsdk/iOS'
```

**Comment by RWOverdijk** [comment]
Hi, sorry I forgot to report that I solved it. @ElvisChiang Slightly different though, perhaps you can tell me if my approach is wrong?

```
target 'MyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  # Pods for MyApp

  target 'MyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by ElvisChiang** [comment]
I would prefer react-native-fbsdk to have the dependencies if no other module pod needs FB* pod.

**Comment by RWOverdijk** [comment]
@ElvisChiang I don't know what that means (never used pods before). But I'll google it. Thanks :) 

In any case, maybe that can be added to the readme here? Then you don't have to add the sdk yourself

**Comment by aghoneim92** [comment]
@RWOverdijk  I noticed that the FBSDK pods are probably for Swift. Since this project is written in Objective-C, it seems that it's not compatible with the pods. When I added the pods from outside this project I got undefined FBSDK objects. Maybe I'm wrong, but that's what happened to me :(

**Comment by RWOverdijk** [comment]
@aghoneim92 I don't know, it works for me. And seeing how it was such a pita to set up I'm mainly happy that it does :p

**Pull request closed without merging**
