### PR TITLE
Removed recursive header files look up from root dir/ios

### PR DESCRIPTION
**Pull request by LukeAvery92**

### CODE REVIEW

**Comment by grisevg** [comment]
+1
Recursively including every single header in the `ios` folder is very dangerous

**Comment by orj** [comment]
+1 To this PR.  Having FB SDK in ~/Documents is not good practice either.

**Comment by sospedra** [comment]
+1 Absolutely necessary

**Comment by sospedra** [comment]
Closed. No merge. No explanation :/

**Pull request closed without merging**
