### PR TITLE
Fixes #416

### LINKED ISSUE #416: Incorrect installation
## Environment

react: 16.6.1 => 16.6.1 
react-native: 0.57.4 => 0.57.4 

## Description

I checked documentation here https://developers.facebook.com/docs/ios/getting-started/ and they said install sdk by cocoapods, so no more copy anything.

But in your documentation said:
Along with FBSDKCoreKit.framework, don't forget to import FBSDKShareKit.framework and FBSDKLoginKit.framework into your Xcode project.

What is the correct way of installation?

### PR DESCRIPTION
**Pull request by kortirso**
Modify readme with valid steps for correct package installation in iOS projects

### CODE REVIEW

**Comment by kortirso** [comment]
Submitted

**Comment by Winglonelion** [comment]
i met some problems when install react-native-fbsdk on ios, and try follow your PR, but i couldn't found `libFBSDKCoreKit.a` . Any ideas for this ?

**Comment by kortirso** [comment]
I just added this to Podfile, and then pod install
pod 'FacebookSDK'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

add RCTFBSDK.xcodeproj to Libraries

and then in Build Phases -> Link Binary With Libraries -> Add, all four *.a were available for adding

so do you have ShareKit and LoginKit, but no CoreKit?

**Comment by kortirso** [comment]
Issue with a problem was here
https://github.com/facebook/react-native-fbsdk/issues/416

**Comment by Winglonelion** [comment]
@kortirso no, like *.framework, i ditn't found any *.a of them

**Comment by kortirso** [comment]
Maybe check search paths

Libraries -> Select RCTFBSDK.xcodeproj -> Build Settings -> Framework Search Paths
I have
~/Documents/FacebookSDK
$(PROJECT_DIR)/../../../ios/Frameworks
$(PROJECT_DIR)/../../../ios/Pods

And For Project -> Build Settings -> Framework Search Paths
I have
$(PROJECT_DIR)/FacebookSDK

**Comment by Winglonelion** [comment]
Here is my `RCTFBSDK.xcodeproj ` framework search path, 

screen shot 2018-11-15 at 3 26 24 pm

My Project frame work search path
screen shot 2018-11-15 at 3 55 53 pm

**Comment by Winglonelion** [comment]
**The good news:** finally, i completed install and implement react-native-fbsdk in my projects. 
But it have some diffrent with your flow: 

- First, because we use `cocoapod` so `$(PROJECT_DIR)/FacebookSDK` is not necessary in project framework searchpath (**exactly we don't need framework search path here**)

- we also don't need any more *.a exept **libRCTFBSDK.a**

- The main problems is we missing headers of Pod dependencies in project. So, add follow path into `Header search paths`
```
${SRCROOT}/Pods/FBSDKCoreKit/FBSDKCoreKit
${SRCROOT}/Pods/FBSDKLoginKit/FBSDKLoginKit
${SRCROOT}/Pods/FBSDKShareKit/FBSDKShareKit
```
#### Note: Because i use `FBSDKCoreKit` instead of `FacebookSDK`, so replace it with your suitable pod dependencies.

And as i think, the real culprit of this issues is the mess of `react-native-fbsdk` documents. We don't have a completed and clarify install and config flow of each case (using cocoapod and using dowloaded framework) 

And with me, using ~/Documents/FacebookSDK is a bad idea, it made CI/CD more complexing and not stable.

Hope too see this soon in your PR

**Comment by kyleschmolze** [comment]
As someone who *also* just battles this for a few hours, THANK YOU @kortirso. 

I do not use Cocoapods, but the step I needed was very simple, I just needed to drag `RCTFBSDK.xcodeproj` from `node_modules/react-native-fbsdk/ios` into `Libraries` in Xcode, so that `libRCTFBSDK.a` would appear as an option to link. Without that step, all the other `*.a` files were linked, but I couldn't find `libRCTFBSDK.a`! Thanks!

**Comment by janicduplessis** [comment]
Going to close this since there hasn't been any activity. Feel free to open another PR if the current installation instructions are still unclear.

**Pull request closed without merging**
