### PR TITLE
return access token with login response

### PR DESCRIPTION
**Pull request by rt2zz**
If the request is not cancelled, this returns the access token with the authentication response.

### CODE REVIEW

**Comment by rt2zz** [comment]
@philikon well I do not know much about objC, but without it I get this compile error: 
screen shot 2015-08-13 at 3 00 13 pm

**Comment by philikon** [comment]
Gotcha. So that's because `result.token` is an `FBSDKCoreKit.FBSDKAccessToken`.

In this case, the two commits aren't really atomic, so perhaps you could squash them into noe and force-update your branch?

**Comment by rt2zz** [comment]
will do tonight

**Comment by philikon** [comment]
Sweet, thank you!

**Comment by rt2zz** [comment]
done

**Comment by rt2zz** [comment]
Got it, and I agree this would be the correct approach. Unfortunately I am not sure if and when I will get around to this. I think it best to close, and I will reopen later if I implement said solution.

Thanks!

**Comment by rt2zz** [comment]
for future reference, the alternative way to access the access token is by calling

```js
var { FBSDKAccessToken } = FBSDKCore;

...

FBSDKAccessToken.getCurrentAccessToken((token) => {
  if (token) {
    console.log(token);
  }
});
```

**Pull request closed without merging**
