### PR TITLE
Let each FBGraphRequestManager object represent its own Batch of GraphRequests

### PR DESCRIPTION
**Pull request by mikelambert**
This fixes https://github.com/facebook/react-native-fbsdk/issues/185

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by mikelambert** [comment]
The alternative to this (which might be a better design!) is to instead store all state in the FBGraphRequestManager JS instance (as part of addRequest and addBatchCallback). And then only call into the native code *once*, during start(), to send all our saved data into the native layer. The native code would then convert the array of requests and batch callback, construct a FBSDKGraphRequestConnection, and start() it.

This would eliminate the need for all state inside RCTFBSDKGraphRequestManager.m/FBGraphRequestModule.java, as well as eliminate the batchId logic, the SelfManagedGraphRequestConnection class, and potentially eliminate any memory leaks due to never-start()ed GraphRequestManager() objects. 

(Sorry I didn't think of this idea earlier. I'm still trying to figure out the best practice for RN native code that  is "a native object", as the traditional example/code/demos really only demonstrate "a list of functions" or "a native React Component")

**Comment by dzhuowen** [comment]
I think the main problem here is how we handle callbacks.  

In the PR, if the developer doesn't add a batchCallback then this batch will not be removed from `mBatchLookup` (see [here](https://github.com/mikelambert/react-native-fbsdk/blob/83b702a385e638b212f1951d746be33aef92155b/Android/src/main/java/com/facebook/reactnative/androidsdk/FBGraphRequestModule.java#L63-L64)). 
For the alternative design, I don't think states and `batchId` can be removed. Suppose we have multiple batch requests going on in a parallel, we still need those to identify which callback to trigger right? And if multiple batch requests running at a time, we shouldn't override the existing callbacks from batch A with the callbacks from batch B, right? 

So either way we need to change the native code to support parallel requests.

**Comment by mikelambert** [comment]
No, I believe you are reading it wrong.

Regardless of `batchCallback`, a `start()`ed request will always be removed from `mBatchLookup`. A `GraphRequestBatchCallback` is constructed in `start()` regardless of whether a `batchCallback` was passed in.

However, there *is* a problem with this PR in that non-start()ed requests will not be deleted from the native storage `mBatchLookup` and `mBatchCallbacks`, which is why I proposed this alternative design.

For the alternative design, I continue to believe that `batchId` can be deleted. Yes, we need to trigger the right callbacks, and we don't want to override them, but my second proposal would not have any problems with that. We would store all the requests, callbacks, and batchcallback state locally in JS, until we call `start()`. Then we would pass all that state to the native side, to construct and start a `GraphRequestBatch`. (These are the native code changes that would be required.) That `GraphRequestBatch` would be initialized with pointers to the necessary callbacks and batchcallbacks as appropriate, and would go off and run them and call them at the appropriate time.

Regardless, this PR does work and support parallelism, and is an improvement over the existing system (in that it supports parallel requests). It has one drawback with native leaking of un-`start()`ed requests. The alternative is unwritten, but would in theory fix it in a cleaner fashion.

**Comment by dzhuowen** [comment]
Ahh.. I overlooked the `GraphRequestBatch` part.
Feel free to submit a another PR for the alternative design if you would like to :-)

**Comment by dzhuowen** [comment]
Thanks for the PR!

**Comment by mikelambert** [comment]
Thanks for merging! I do agree the alternative I proposed will be better/cleaner, but sorry I haven't had the time to rewrite it since the existing solution I wrote first was working for my project's needs. If I ever get free time to do it properly, I'll submit another PR though. Thanks!

**Pull request merged**
