### PR TITLE
Remove some files from the repo, use files instead of .npmignore

### PR DESCRIPTION
**Pull request by janicduplessis**
Those things were probably useful when this was in fb internal repo but we can remove them now.

### CODE REVIEW

**Comment by dozoisch** [comment]
Hi @janicduplessis ! Just noticed that this PR removed ios_setup.js but this is the way mentionned in the official documentation.

https://developers.facebook.com/docs/react-native/configure-ios


image

**Comment by janicduplessis** [comment]
@dozoisch Thanks for pointing it out, I'll see if I can get this doc updated. The installation instructions [here](https://github.com/facebook/react-native-fbsdk#32-ios) should work. However I think we should update the instruction to recommend using CocoaPods.

**Comment by dozoisch** [comment]
@janicduplessis perfect thanks!

**Comment by hugoh59** [comment]
I'm having this issue as well.

**Pull request merged**
