### PR TITLE
Allow the parameter to be ""

### PR DESCRIPTION
**Pull request by mikelambert**
Sometimes I want to pass "?metadata=1&fields=", but passing {metadata: {string: '1'}, fields: {string: ''}} breaks on the above code. This fixes it.

### CODE REVIEW

**Comment by mingflifb** [comment]
Can you comment on why you'd want fields=''?

**Comment by mikelambert** [comment]
I gave an example in my description above. where I want the metadata of an object, and don't care about the fields. 

If you want me to get really specific:
- I have an event, which returns the organizers of the event as ids
- I want to link to those organizers with `fb://` URL scheme in the app to open to the right page
- However, depending on whether those ids represent a Page or a User, I must link to them differently (ugh)
- So I must query FB to know if they are a page or a user. The best way to query this is to do a `/id?metadata=1` query, and then retrieve `metadata.type`.
- I thought (though I can no longer find the code where this happens, and seems it no longer is a problem) that it required me to pass a fields= in a modern SDK call, instead of trying to request the default set of fields. So passing fields='' satisfied it, at the time. But perhaps I misread it...? I didn't want to retrieve any "default" set of fields.
- But fields="" broke the fbsdk.

I can remove the fields="" in my code, and things seem to work okay now. Not sure what error I saw that made me add it. But regardless, the error message presented (must have a 'string' field) is inconsistent with what the check does, and this fixes the check. Alternately, one should fix the error message. I wasted some time trying to debug this one, confused by why I was getting this message since I was passing it correctly.

**Comment by mikelambert** [comment]
Thoughts?

**Comment by facebook-github-bot-3** [comment]
@mikelambert updated the pull request - [view changes](https://github.com/facebook/react-native-fbsdk/pull/246/files/e32f9145ebb441387ae3b2fdbfea0b092bfd184b..8bead6ca6d03a95cd4278dc6cf2f7fe4cfaf4d4f)

**Comment by mikelambert** [comment]
Um, can you clarify why you closed this, @dzhuowen ?

**Comment by mingflifb** [comment]
There's a very simple workaround, which is to specify fields=id, since the id field will always exist. You also shouldn't try to link to fb:// because those deep links are not documented/guaranteed, and will also only work if the FB app is installed. You should instead use fields=link and use that http url as the actual link.

**Comment by mikelambert** [comment]
So you would prefer that I use a workaround, as opposed to merging a provided fix that avoids the need for a workaround in the first place?

I don't get it.

Is there a reason you *don't* want this fix? I haven't seen a justification provided.

If you really don't want this fix, and want others to go through the same confusing hassle I did, then you should at least fix your error message. Your error message is currently misleading and wrong, suggesting the caller needs to pass an object with a string field (which I did!). My change fixes this...but if you don't like my change, I suggest you fix the error message instead.

**Comment by mikelambert** [comment]
And thank you about the advice on fb:// URLs. It is possible to check if the device supports fb:// URLs before sending a user to them. So if the device does not support fb:// URLs, then yes I send them through to the web URL.

**Comment by mingflifb** [comment]
IMO this does not address the main issue, and having a fields='', while may fix your particular problem, does not make semantic sense (passing fields = nothing to a graph request does not make sense). The message you see is also not an error, but a warning message, and can be safely ignored.

On your point about fb:// urls, while it's possible to check whether the scheme is supported on a device, my point is that you're using undocumented behavior, and it may change at any time with an update to the FB app, and I would discourage that particular usage.

**Comment by mikelambert** [comment]
As you can see here, `fields=` works correctly in the Graph API Explorer, and I assumed that I could do something similar with the fbsdk:
https://developers.facebook.com/tools/explorer/145634995501895/?session_id=1537513972975347

Remember, it was the FBSDK that required me to pass a `fields=` in the first place...again the Graph API Explorer lets me request a naked `metadata=1` call:
https://developers.facebook.com/tools/explorer/145634995501895/?session_id=149849105601059

But when attempting to pass `{metadata: {string: '1'}, fields: {string: ''}}`, I was instead given a confusing error about how my `fields` key needed to have a `string` field...despite explicitly passing a `string` field! Note, this was not a "safely ignorable warning", this was a `throw new Error` that is never caught, according to my reading of the code.

I hope you can understand my frustration here. There are two instances where I can use the Graph API Explorer, that FB SDK didn't let me do:
(a) a `metadata=1` call
(b) a `metadata=1&fields=` call. (I didn't think of the creative `fields=id` workaround to satisfy the SDK)
And then on top of that, the error message for (b) was actually _wrong_, telling me I needed to do something I already did.

I can understand that this is your project, and you feel like my change is not the direction you want to go. But I hope you can understand that as an actual developer using this (coming from a server background where these API calls Just Work)....the development experience, and error messages, are just plain confusing, and I have to dig in and trace through the source to figure out WTF is going on.

So from my perspective, there are multiple points here in which this process can be improved, and I am frustrated that you seem to believe that none of them are justified, and that my experience here is "Normal".

**Comment by mingflifb** [comment]
The SDK will let you use a `metadata=1` call.

The `fields` parameter, while not required, is heavily recommended. This is why if you don't pass in any fields param for a GET request, the SDK will generate a warning. However, this is not an error, and will not affect how the actual graph request is made. 

The error you're seeing is because you're passing in an empty fields param (which arguably could also be a warning, but semantically doesn't make much sense even if the server side is more fault tolerant and allows it). The SDK in certain cases will be more strict than what the server side allows in order to prevent some mistakes. Your change also applies to all params (and not just `fields`, which means the SDK would allow empty strings for other params which may actually cause errors server side).

In your specific case, you can use `{metadata: {string: '1'}}` and ignore the warning, or use the workaround I provided above.

I understand your frustration and apologize that we didn't provide more context before closing this, but I do believe this PR was too generic and didn't address the core issue. There is also a [bug tool](https://developers.facebook.com/bugs) for you to report bugs on the SDKs that Facebook supports.

**Comment by mikelambert** [comment]
Okay, thank you for your time and patience in explaining your perspective, I appreciate it even if I disagree.

However, I still believe the error message should be changed to say "Please pass a non-empty-valued string" or something more accurate than the message that exists now, but I've fully explained my perspective, and will not argue this any more.

**Pull request closed without merging**
