### PR TITLE
Add podspec

### PR DESCRIPTION
**Pull request by emroot**
## Wh(at|y)??
For those of us that prefer to stick to `podspec`.
See this: https://github.com/facebook/react-native-fbsdk/issues/210

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by emroot** [comment]
I signed the CLA, but somehow not showing up here :/

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by idris** [comment]
Any chance of a version bump for this, so we can get it from npm?

**Comment by dzhuowen** [comment]
Done.

**Pull request merged**
