### PR TITLE
Update iOS RN header paths

### PR DESCRIPTION
**Pull request by janicduplessis**
https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d moves header imports to `<React/*>`. This updates header include path and all imports so build works against react master (soon to be version 0.40.0).

TODO: Fix / update sample when 0.40 is out.

### CODE REVIEW

**Comment by radko93** [comment]
The problem already exists in 0.39, maybe we should merge it now?

**Comment by janicduplessis** [comment]
The change is only part of 0.40 according to tags on https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d. There was a bit of discussion around it and seems like the change to header paths won't be needed anymore but all imports will still need to be updated. Will update this PR once this is settled.

Also take note that this change is NOT backwards compatible sadly so we have to depend on RN 0.40+ after merging this.

**Comment by jpapillon** [comment]
@janicduplessis I'm trying to migrate to 0.39.2, but I can't because this hasn't been merged yet. Any plans on merging it soon? Thanks!

**Comment by janicduplessis** [comment]
@jpapillon Are you sure this is needed for 0.39? According to the tags on the github commit this is only part of 0.40 https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d

**Comment by ptomasroos** [comment]
We're facing same issue. Unable to run current version on 0.39 but Your branch works on 0.39. Gave it 2h to try to understand it. Makes no sense at all. 😳

**Comment by jpapillon** [comment]
@janicduplessis 0.39.2, yes. Works fine on 0.38!

**Comment by Andreyco** [comment]
RnFbSDK is not working on 0.39.2.
Works good on 0.39.0 though

**Comment by danieldkim** [comment]
Hi, RN 0.40.0 has been released.  Any plans to merge this and push out a new distro?

**Comment by nicolabortignon** [comment]
Please can someone merge this? 
Now that RN 0.40.0 is out this is becoming more and more urgent.

**Comment by Amurmurmur** [comment]
Guys do you experience the same thing? AccessToken.getCurrentAccessToken() returns null after application restart, even tho it returns valid access token after a successful login.

**Comment by danieldkim** [comment]
fwiw, installing the package from @janicduplessis's fork works for me.  i'm only using the login functionality but in principle everything else should work as well as there haven't been any changes since the 0.4.0 release and all this PR does is update the import statements to work with RN 0.40.0.

**Comment by Amurmurmur** [comment]
Did you use LoginManager? And than check AccessToken to check for its existence on application boot. Though react-native-facebook-login with its' default login button also resets to Login state after app restart. Would so much appreciate if you can help.

**Comment by monzerhijazi** [comment]
+1 please merge

**Comment by Amurmurmur** [comment]
AccessToken is null after app restart - thats the bug of Facebook SDK 4.18, switched to 4.17 and everything works like a charm :) Hope that helps everyone else who came to the same issue.

**Comment by dzhuowen** [comment]
Thanks for the PR! We'll release a new version soon.

**Comment by christiangenco** [comment]
For the impatient, you can install the latest version with this fix from github right now with:

    react-native install "facebook/react-native-fbsdk"

This will write to your `package.json` file:

    "react-native-fbsdk": "github:facebook/react-native-fbsdk"

(you'll probably want to `react-native uninstall react-native-fbsdk` to uninstall and unlink the currently released version)

I also had to manually run `react-native link react-native-fbsdk`, then remove and re-add `LIBRCTFBSDK.a` from `Build Phases`/`Link Binary With Libraries` in XCode.

**Comment by kurtfunai** [comment]
Thank you @christiangenco! Huge help.

**Comment by jpapillon** [comment]
Thanks @dzhuowen! Can't wait for the new release! :)

**Comment by geniusgordon** [comment]
Thanks for the PR!
When can we get the new version on npm?

**Comment by hramos** [comment]
The new version should be published to npm later this week.

**Comment by tonygriv** [comment]
I have **FBSDKCoreKit/FBSDKCoreKit.h file not found error** and spent several hours trying to solve it, but can't understand whats going wrong((

Any ideas?

react-native 0.40
react-native-fsdk 0.5.0

**Comment by Amurmurmur** [comment]
Try on of the following:
1. Check if you did `react-native link` on your RN project
2. Manually check in `Linked Frameworks And Libraries`, that you have `libRCTFBSDK.a` if not, hit that + button at the bottom and link it.
3. When upgrading the project itself react-native from <0.40 make sure you ran `react-native upgrade` after you've the module itself with `npm install react-native@latest --save`, because somethings might be changed in the linking and other project settings, and obviously the change in the header paths.
4. Try:
```
rm -rf ./node_modules
watchman watch-dell-all
npm cache clean
npm install
react-native run-ios/run-android
```

Hopefully it helps

**Comment by tonygriv** [comment]
@Amurmurmur, now I  have Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBSDKHashtag", referenced from:
      objc-class-ref in libRCTFBSDK.a(RCTConvert+FBSDKSharingContent.o) error.

God damn, I can't build fbsdk a couple of days!((

**Comment by Amurmurmur** [comment]
@tonygriv Have you imported necessary frameworks from the FacebookSDK folder into the xcode project? 
This ones:
screen shot 2017-02-04 at 23 14 35

**Comment by tonygriv** [comment]
Yes. 
screen shot 2017-02-04 at 23 16 12

**Comment by tannerhallman** [comment]
For what it's worth, when it is working and I happen to run `react-native link` it breaks and I have to remove my /node_modules and npm install again.

**Comment by teloconf** [comment]
RCTFBSDKInitializer.m:22:9: fatal error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
#import <FBSDKCoreKit/FBSDKCoreKit.h>

 "react-native": "0.41.2",
  "react-native-fbsdk": "^0.5.0"

Any Idea? 
Thanks

**Comment by teloconf** [comment]
SOLVED!

1.- react-native uninstall react-native-fbsdk
2.- Remove Facebook Frameworks from XCode
3.- Add Facebook Frameworks from XCode
4.- react-native install react-native-fbsdk
5.- react-native link react-native-fbsdk

**Comment by teloconf** [comment]
**Solution 2:**
XCode -> Project Navigator -> Libraries -> RCTFBSDK.xcodeproject -> Frameworks -> Delete the files and copy the same as in the Frameworks folder of the project root except Bolts.framework

**Comment by VGamezz19** [comment]
Hello there! 
There is a similar [problem](https://github.com/facebook/react-native/issues/17957) but with **RCTFBLoginButton**
Do you think it is by the FBSDK or by RC?

**Pull request merged**
