### PR TITLE
Update Readme for iOS compilation problem

### PR DESCRIPTION
**Pull request by ishigamii**
***all the steps except the pod install (Step 2)*** 
Using : 
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-fbsdk": "^0.8.0",
```
In the step 2 of the guide it is suggested to add `pod 'FacebookSDK'` which is creating issues in the iOS  project with the `react-native-fbsdk` lib

**Example of issues :** 

During `react-native run-ios`: 
```
** BUILD FAILED **

The following build commands failed:

    CompileC /Users/xxx/Documents/ReactJS/xxx/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKCoreKit.build/Objects-normal/x86_64/FBSDKAccessTokenCache.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/TokenCaching/FBSDKAccessTokenCache.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

on Xcode : 
```
Duplicate interface definition for class 'FBSDKAccessToken'
```

### CODE REVIEW

**Comment by codytwinton** [comment]
@ishigamii Thanks for contributing this PR! Can you sign the Facebook CLA?

**Comment by ishigamii** [comment]
@codytwinton I just sign it

**Comment by noahtallen** [comment]
If someone (like me) wants to use Pods for managing the native dependencies instead of manually downloading the file, they can use `pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'` instead of `pod 'FacebookSDK'`. I think this might be a good addition to the readme here

**Comment by codytwinton** [comment]
@ishigamii - There is a merge conflict. Once resolved, I can merge this PR.

**Comment by ishigamii** [comment]
@codytwinton should be good now

**Pull request merged**
