### PR TITLE
Update podspec dependencies version

### LINKED ISSUE #644: -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. in react native ios 13 new upodate issue

### PR DESCRIPTION
**Pull request by suraneti**
Fixes #644 #646 

**Problem**

- `-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed.` on iOS 13

- `logInWithReadPermissions returning isCancelled value always true`

**Solution**
- Update podspec dependencies version from '5.0.0' to '5.6.0'

### CODE REVIEW

**Comment by binwilly** [comment]
worked for me!

**Comment by janicduplessis** [comment]
Published as 0.10.3

**Comment by jacquesdev** [comment]
This fix did not work directly for me, I had to do that, and then also call the method LoginManager.logInWithPermissions instead of LoginManager.logInWithReadPermissions.

@janicduplessis - is this the right method name for 0.10.3?

**Comment by suraneti** [comment]
@jacquesdev **Breaking changes from 0.10.0** 
LoginManager: `logInWithReadPermissions` and `logInWithWritePermissions` have been replaced with `logInWithPermissions`

**Pull request merged**
