### PR TITLE
Adds native-only props to all views

### PR DESCRIPTION
**Pull request by martinarroyo**
There seems to be some issues with the new version of the native SDK (which is installed automatically by Gradle) and this package (for both versions 0.5 and 0.6). I don't like this fix, since every native view that I have programmed does not require this kind of setup. But it is the only solution I found in order to be able to continue developing my app.

### CODE REVIEW

**Comment by tugorez** [comment]
Hi @martinarroyo, just a question here.
Is this related to https://github.com/facebook/react-native-fbsdk/pull/339 ?

**Comment by martinarroyo** [comment]
@tugorez I am not entirely sure. We actually got stuck with what #339 describes, but I think we fixed that one by upgrading to the Android build tools and other stuff that was required. Then this issue happened :)

**Comment by dzhuowen** [comment]
Hi @martinarroyo why do you need this change? These properties are not used in the native component. If it's convenient for you can you point me to a sample project with the error repo?

**Comment by martinarroyo** [comment]
@dzhuowen This change is needed because otherwise the SDK makes my App crash. The native component does indeed use the props, as it inherits from the base view classes and the properties are explicitly added to the code (by passing `ViewPropTypes` to the `propTypes`). So we either need this change so that no prop binding is established to those props or some other better solution (maybe `@providesModule` might do the trick). I might be able to create a sample project to replicate it, if I find the time.

**Comment by martinarroyo** [comment]
@dzhuowen I set up a repo that replicates the issue: https://github.com/martinarroyo/FBSDKBug It uses RN 0.42 since I could not replicate with the latest version of React Native (0.44.0 at this time). However, I now stumbled upon https://github.com/facebook/react-native/issues/14360 (which was solved with just `yarn add prop-types`). In any case, you can replicate the issue by just running the `master` branch. If you `git checkout` the `with-fix` branch, which only changes the `react-native-fbsdk` in `package.json` to point to the fixed version of the SDK, you will see a 'Login with Facebook' button.

**Comment by jccarrillo** [comment]
Any progress on this PR? This issue is also affecting me. Thanks!

**Comment by veebuv** [comment]
Any updates on this ? Thank you :)

**Comment by thillsman** [comment]
This PR fixes the `LikeView has no propType for native prop RCTFBLikeView.onLayout of native type boolean` issue for our team. We'd love if it were merged.

**Comment by janicduplessis** [comment]
Native only props no longer exist in RN so we can close this.

**Pull request closed without merging**
